package com.example.schoolclub.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RegistrationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRegistrationAllPropertiesEquals(Registration expected, Registration actual) {
        assertRegistrationAutoGeneratedPropertiesEquals(expected, actual);
        assertRegistrationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRegistrationAllUpdatablePropertiesEquals(Registration expected, Registration actual) {
        assertRegistrationUpdatableFieldsEquals(expected, actual);
        assertRegistrationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRegistrationAutoGeneratedPropertiesEquals(Registration expected, Registration actual) {
        assertThat(actual)
            .as("Verify Registration auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRegistrationUpdatableFieldsEquals(Registration expected, Registration actual) {
        assertThat(actual)
            .as("Verify Registration relevant properties")
            .satisfies(a -> assertThat(a.getRegistrationDate()).as("check registrationDate").isEqualTo(expected.getRegistrationDate()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRegistrationUpdatableRelationshipsEquals(Registration expected, Registration actual) {
        assertThat(actual)
            .as("Verify Registration relationships")
            .satisfies(a -> assertThat(a.getClub()).as("check club").isEqualTo(expected.getClub()));
    }
}
